validator: Parse every schema in tests
SpaceApi/validator pull request #9
Opened 2017-01-09 08:24 UTC by rnestler

We use `expect()` after parsing the schema, so we should guarantee that
the schema actually parses.

2017-01-09 08:25 UTC, rnestler commented
There are no tests with parameters in Rust currently, are there?

2017-01-09 13:15 UTC, dbrgn commented
> so we should guarantee that the schema actually parses.

Good point! :)

> There are no tests with parameters in Rust currently, are there?

Not by default, as far as I know. Should be doable with a macro though.

https://stackoverflow.com/questions/34662713/how-can-i-create-parameterized-tests-in-rust

Here are two interesting testing frameworks (albeit without parametrization):

https://github.com/reem/stainless
https://github.com/BurntSushi/quickcheck

2017-01-10 09:59 UTC, dbrgn commented
What about a macro to generate these test cases?

2017-01-11 21:15 UTC, dbrgn requested changes
What about a macro to generate these test cases?

2017-01-11 22:36 UTC, rnestler commented
> What about a macro to generate these test cases?

Like this? Also: Yay first Rust macro 😊

2017-01-12 07:55 UTC, dns2utf8 commented
I like the macros

2017-01-12 08:19 UTC, dbrgn approved these changes
Looks good :)

2017-01-12 08:26 UTC, dns2utf8 approved these changes
🏳️‍🌈

2017-01-12 09:03 UTC, rnestler commented
>  Also: Yay first Rust macro :blush:

I just noticed this is wrong... I wrote a macro for the custom ToJson serialization in spaceapi-rs with the Optional type.

2017-01-12 09:56 UTC, merged